A=int(input("Enter number= "))
B=int(input("Enter another number="))
print("radikal A:",end=" ")
print (math.sqrt(A))
print("radikal B:",end=" ")
print (math.sqrt(B))

print("sin A:",end=" ")
print (math.sin(A))
print("sin B:",end=" ")
print (math.sin(B))

print("cos A:",end=" ")
print (math.cos(A))
print("cos B:",end=" ")
print (math.cos(B))

print("tan A:",end=" ")
print (math.tan(A))
print("tan B:",end=" ")
print (math.tan(B))

print("A+B=",A+B)
print("A-B=",A-B)
print("A*B=",A*B)
print("A/B=",A/B)